server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: node-service
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queues:
      textMessageUpdate: ${RABBIT_TEXT_MESSAGE_UPDATE_QUEUE}
      photoMessageUpdate: ${RABBIT_PHOTO_MESSAGE_UPDATE_QUEUE}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}