server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: node-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    queues:
      textMessageUpdate: ${RABBIT_TEXT_MESSAGE_UPDATE_QUEUE}
      photoMessageUpdate: ${RABBIT_PHOTO_MESSAGE_UPDATE_QUEUE}
      answerMessage: ${RABBIT_ANSWER_MESSAGE_QUEUE}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}